# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'DYDemo' do

  # Pods for DYDemo

  target 'DYDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DYDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire'

end
